// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build darwin && arm64

package embed

import _ "embed"

//go:embed assets/upgrade-shim-darwin-arm64.zst
var embeddedUpgradeShim_darwin_arm64 []byte

func init() {
	register(Asset{
		SourceDigest: "b5304214ae8e4e3f28e63c6215fd8c5c398c76d3e92f7e6bb3457d28893984a1",
		SHA256:       "ba75162ab9fff59b66501a5198d2b6088e99eeb91abba8e22dc9af19127683b7",
		Zstd:         embeddedUpgradeShim_darwin_arm64,
	})
}
