// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build darwin && arm64

package embed

import _ "embed"

//go:embed assets/upgrade-shim-darwin-arm64.zst
var embeddedUpgradeShim_darwin_arm64 []byte

func init() {
	register(Asset{
		SourceDigest: "50f7536dc418d30689b535724c2f0de057601b7e31bbe20fab9426f25b1831b5",
		SHA256:       "b33685278ca89c4da9653557c1446c32ead3c515518beef163884e55ab9699ed",
		Zstd:         embeddedUpgradeShim_darwin_arm64,
	})
}
