// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build darwin && arm64

package embed

import _ "embed"

//go:embed assets/upgrade-shim-darwin-arm64.zst
var embeddedUpgradeShim_darwin_arm64 []byte

func init() {
	register(Asset{
		SourceDigest: "304e34417cf49a466bae1e621cbae57b07cc8ea96bab5dc0a18a0b8da6392883",
		SHA256:       "be209704f6eed5229cda38cf7959fad9a887a02452a5a6453ee1750fa698085e",
		Zstd:         embeddedUpgradeShim_darwin_arm64,
	})
}
