#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PACKAGE_DIR="${ROOT_DIR}/internal/upgradeshim/embed"
ASSET_DIR="${PACKAGE_DIR}/assets"
GOOS_VALUE="${1:-${GOOS:-$(go env GOOS)}}"
GOARCH_VALUE="${2:-${GOARCH:-$(go env GOARCH)}}"
SCRIPT_PATH="${BASH_SOURCE[0]}"

checksum_cmd=(sha256sum)
if ! command -v "${checksum_cmd[0]}" >/dev/null 2>&1; then
  checksum_cmd=(shasum -a 256)
fi

checksum_first_field() {
  "${checksum_cmd[@]}" "$1" | awk '{print $1}'
}

asset_name="upgrade-shim-${GOOS_VALUE}-${GOARCH_VALUE}"
generated_go="${PACKAGE_DIR}/upgrade_shim_${GOOS_VALUE}_${GOARCH_VALUE}_embed.go"
generated_go_tmp="${generated_go}.tmp.$$"
compressed_path="${ASSET_DIR}/${asset_name}.zst"

source_digest="$(
  {
    printf 'goversion=%s\n' "$(go env GOVERSION)"
    printf 'script=%s\n' "$(checksum_first_field "${SCRIPT_PATH}")"
    {
      printf '%s\n' "${ROOT_DIR}/go.mod" "${ROOT_DIR}/go.sum"
      CGO_ENABLED=0 GOOS="${GOOS_VALUE}" GOARCH="${GOARCH_VALUE}" \
        go list -tags codex_upgrade_shim -deps \
          -f '{{if not .Standard}}{{ $dir := .Dir }}{{range .GoFiles}}{{$dir}}/{{.}}{{"\n"}}{{end}}{{range .CgoFiles}}{{$dir}}/{{.}}{{"\n"}}{{end}}{{range .EmbedFiles}}{{$dir}}/{{.}}{{"\n"}}{{end}}{{end}}' \
          ./cmd/upgrade-shim
    } | sort -u | while IFS= read -r file; do
      # The generated shim asset embeds itself through the install package.
      # Excluding that package avoids a recursive digest.
      if [[ "${file}" == "${ROOT_DIR}/internal/upgradeshim/embed/"* ]]; then
        continue
      fi
      if [[ "${file}" == "${ROOT_DIR}/"* && -f "${file}" ]]; then
        printf '%s  %s\n' "$(checksum_first_field "${file}")" "${file#"${ROOT_DIR}/"}"
      fi
    done
  } | "${checksum_cmd[@]}" | awk '{print $1}'
)"

if [[ -f "${generated_go}" && -f "${compressed_path}" ]] && grep -Fq "SourceDigest: \"${source_digest}\"" "${generated_go}"; then
  echo "upgrade shim asset already up to date for ${GOOS_VALUE}/${GOARCH_VALUE}" >&2
  exit 0
fi

if ! command -v zstd >/dev/null 2>&1; then
  echo "zstd is required to prepare upgrade shim assets" >&2
  exit 1
fi

tmp_dir="$(mktemp -d)"
cleanup() {
  rm -rf "${tmp_dir}"
  rm -f "${generated_go_tmp}"
}
trap cleanup EXIT

binary_path="${tmp_dir}/${asset_name}"
if [[ "${GOOS_VALUE}" == "windows" ]]; then
  binary_path="${binary_path}.exe"
fi

CGO_ENABLED=0 GOOS="${GOOS_VALUE}" GOARCH="${GOARCH_VALUE}" \
  go build -tags codex_upgrade_shim -trimpath -ldflags "-s -w" -o "${binary_path}" ./cmd/upgrade-shim

binary_sha256="$(checksum_first_field "${binary_path}")"

mkdir -p "${ASSET_DIR}"
zstd -19 -q -f -o "${compressed_path}" "${binary_path}"

cat > "${generated_go_tmp}" <<EOF
// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build ${GOOS_VALUE} && ${GOARCH_VALUE}

package embed

import _ "embed"

//go:embed assets/$(basename "${compressed_path}")
var embeddedUpgradeShim_${GOOS_VALUE}_${GOARCH_VALUE} []byte

func init() {
	register(Asset{
		SourceDigest: "${source_digest}",
		SHA256:       "${binary_sha256}",
		Zstd:         embeddedUpgradeShim_${GOOS_VALUE}_${GOARCH_VALUE},
	})
}
EOF

gofmt -w "${generated_go_tmp}"
mv "${generated_go_tmp}" "${generated_go}"
echo "prepared upgrade shim asset for ${GOOS_VALUE}/${GOARCH_VALUE}" >&2
